'use client'
import { CSSProperties, useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
export interface DriftWallItem { image:string; title?:string; href?:string }
export interface DriftWallProps { items?:DriftWallItem[]; columns?:number; tileWidth?:number; tileHeight?:number; gap?:number; radius?:number; tilt?:number; turn?:number; roll?:number; perspective?:number; depth?:number; speed?:number; direction?:'up'|'down'; variance?:number; parallax?:number; pauseOnHover?:boolean; lift?:number; fade?:number; dim?:number; grayscale?:boolean; overlayColor?:string; className?:string; style?:CSSProperties }
const cx=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(' ')
const defaults=Array.from({length:15},(_,i)=>({image:`https://picsum.photos/id/${[1015,1025,1039,1043,1044,1050,1062,1069,1074,1080,1084,106,110,133,164][i]}/600/400`,title:`Tile ${i+1}`}))
export default function DriftWall({items=defaults,columns=5,tileWidth=200,tileHeight=132,gap=18,radius=14,tilt=16,turn=-14,roll=0,perspective=1200,depth=120,speed=42,direction='up',variance=.45,parallax=.6,pauseOnHover=false,lift=64,fade=.6,dim=.55,grayscale=false,overlayColor='#060010',className='',style}:DriftWallProps){
 const root=useRef<HTMLDivElement>(null), plane=useRef<HTMLDivElement>(null), tracks=useRef<(HTMLDivElement|null)[]>([]), raf=useRef<number>(), last=useRef<number>(), offsets=useRef<number[]>([]), velocities=useRef<number[]>([]), pointer=useRef({x:0,y:0}), damped=useRef({x:0,y:0}), hovered=useRef(-1), wall=useRef(false), activeRef=useRef<string|null>(null); const [height,setHeight]=useState(600),[active,setActive]=useState<string|null>(null),[reduced,setReduced]=useState(false)
 useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const fn=()=>setReduced(mq.matches);mq.addEventListener('change',fn);return()=>mq.removeEventListener('change',fn)},[])
 const cols=useMemo(()=>{const out:Array<DriftWallItem[]>=Array.from({length:columns},()=>[]);items.forEach((x,i)=>out[i%columns].push(x));return out.map(x=>x.length?x:items.slice(0,1))},[items,columns]); const unit=tileHeight+gap; const meta=useMemo(()=>cols.map(col=>{const copyHeight=Math.max(unit,col.length*unit);return {copyHeight,copies:Math.max(2,Math.ceil(height*1.6/copyHeight)+1)} }),[cols,unit,height]); const base=useMemo(()=>cols.map((_,i)=>speed*(1+variance*(((i*.618+.35)%1)*2-1))*(direction==='up'?1:-1)*(i%2? -1:1)),[cols,speed,variance,direction])
 useLayoutEffect(()=>{if(!root.current)return;const ro=new ResizeObserver(([e])=>setHeight(e.contentRect.height||600));ro.observe(root.current);return()=>ro.disconnect()},[]); useEffect(()=>{offsets.current=meta.map((m,i)=>m.copyHeight*((i*.37)%1));velocities.current=cols.map(()=>0)},[meta,cols])
 const activate=useCallback((id:string,c:number)=>{activeRef.current=id;hovered.current=c;setActive(id)},[]);const release=useCallback(()=>{activeRef.current=null;hovered.current=-1;setActive(null)},[])
 useEffect(()=>{const frame=(ts:number)=>{if(last.current===undefined)last.current=ts;const dt=Math.min(.05,Math.max(0,ts-last.current)/1000);last.current=ts;const d=1-Math.exp(-dt/.12);damped.current.x+=(pointer.current.x*parallax*8-damped.current.x)*d;damped.current.y+=(-pointer.current.y*parallax*8-damped.current.y)*d;if(plane.current)plane.current.style.transform=`translate(-50%,-50%) scale(1.18) rotateX(${tilt+damped.current.y}deg) rotateY(${turn+damped.current.x}deg) rotateZ(${roll}deg) translateZ(${-depth}px)`;tracks.current.forEach((el,c)=>{const m=meta[c];if(!el||!m)return;if(!reduced){const target=base[c]*((wall.current&&pauseOnHover)||hovered.current===c?0:1);velocities.current[c]+=(target-velocities.current[c])*(1-Math.exp(-dt/.28));offsets.current[c]=((offsets.current[c]+velocities.current[c]*dt)%m.copyHeight+m.copyHeight)%m.copyHeight}el.style.transform=`translate3d(0,${-offsets.current[c]}px,0)`});raf.current=requestAnimationFrame(frame)};raf.current=requestAnimationFrame(frame);return()=>{if(raf.current)cancelAnimationFrame(raf.current);last.current=undefined}},[base,meta,reduced,pauseOnHover,parallax,tilt,turn,roll,depth])
 const vars=useMemo(()=>({'--dw-w':`${tileWidth}px`,'--dw-h':`${tileHeight}px`,'--dw-gap':`${gap}px`,'--dw-radius':`${radius}px`,'--dw-lift':`${lift}px`,'--dw-dim':dim,'--dw-gray':grayscale?1:0,'--dw-overlay':overlayColor,'--dw-edge':`${(1-fade)*100}%`,perspective:`${perspective}px`,...style} as CSSProperties),[tileWidth,tileHeight,gap,radius,lift,dim,grayscale,overlayColor,fade,perspective,style])
 const move=(e:React.PointerEvent<HTMLDivElement>)=>{const r=root.current?.getBoundingClientRect();if(!r)return;pointer.current={x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5};const tile=(document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tile]') as HTMLElement|null);if(tile&&tile.dataset.id!==activeRef.current){activeRef.current=tile.dataset.id||null;hovered.current=Number(tile.dataset.col);setActive(activeRef.current)}}
 const tile=(item:DriftWallItem,id:string,col:number)=>{const content=<span className="pointer-events-none absolute inset-[calc(var(--dw-gap)/2)] block overflow-hidden rounded-[var(--dw-radius)] bg-[#0b0b12] opacity-[var(--dw-dim)] transition-[transform,opacity] duration-[420ms] group-[.is-active]/tile:opacity-100 group-[.is-active]/tile:[transform:translateZ(var(--dw-lift))]"><img src={item.image} alt={item.title||''} className="h-full w-full object-cover object-center grayscale-[var(--dw-gray)]" loading="lazy"/><span className="absolute inset-0 bg-[var(--dw-overlay)] opacity-40"/></span>;const props={className:cx('group/tile relative block h-[calc(var(--dw-h)+var(--dw-gap))] w-full flex-none [transform-style:preserve-3d]',active===id&&'is-active'),'data-tile':true,'data-id':id,'data-col':col,onFocus:()=>activate(id,col),onBlur:release};return item.href?<a href={item.href} {...props}>{content}</a>:<div tabIndex={0} role="button" aria-label={item.title||'Gallery tile'} {...props}>{content}</div>}
 return <div ref={root} className={cx('relative flex h-full w-full items-center justify-center overflow-hidden',className)} style={vars} onPointerMove={move} onPointerEnter={()=>{wall.current=true}} onPointerLeave={()=>{wall.current=false;pointer.current={x:0,y:0};release()}} role="group" aria-label="Drifting wall gallery"><div ref={plane} className="absolute left-1/2 top-1/2 flex [transform-style:preserve-3d]"><div className="flex items-center justify-center">{cols.map((col,c)=><div key={c} className="relative w-[calc(var(--dw-w)+var(--dw-gap))]"><div ref={el=>{tracks.current[c]=el}} className="flex flex-col">{Array.from({length:meta[c].copies}).flatMap((_,copy)=>col.map((item,i)=>tile(item,`${c}-${copy}-${i}`,c)))}</div></div>)}</div></div></div>
}
