'use client'
import React, { forwardRef, useMemo, useRef, useLayoutEffect, useEffect } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Color, Mesh, ShaderMaterial } from 'three'

const rgb=(hex:string)=>{const c=hex.replace('#','');return [parseInt(c.slice(0,2),16)/255,parseInt(c.slice(2,4),16)/255,parseInt(c.slice(4,6),16)/255] as [number,number,number]}
const vertex=`varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`
const fragment=`varying vec2 vUv; uniform float uTime,uSpeed,uScale,uRotation,uNoiseIntensity; uniform vec3 uColor; float noise(vec2 p){float e=2.71828;vec2 r=e*sin(e*p);return fract(r.x*r.y*(1.0+p.x));} vec2 rot(vec2 uv,float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c)*uv;} void main(){float rnd=noise(gl_FragCoord.xy);vec2 tex=rot(vUv*uScale,uRotation)*uScale;float t=uSpeed*uTime;tex.y+=.03*sin(8.*tex.x-t);float pattern=.6+.4*sin(5.*(tex.x+tex.y+cos(3.*tex.x+5.*tex.y)+.02*t)+sin(20.*(tex.x+tex.y-.1*t)));vec4 col=vec4(uColor,1.)*pattern-rnd/15.*uNoiseIntensity;gl_FragColor=vec4(col.rgb,1.);}`
function Plane({uniforms}:{uniforms:any}){const ref=useRef<Mesh>(null);const {viewport}=useThree();useLayoutEffect(()=>{ref.current?.scale.set(viewport.width,viewport.height,1)},[viewport]);useFrame((_,d)=>{if(ref.current)(ref.current.material as ShaderMaterial).uniforms.uTime.value+=.1*d});return <mesh ref={ref}><planeGeometry args={[1,1]}/><shaderMaterial uniforms={uniforms} vertexShader={vertex} fragmentShader={fragment}/></mesh>}
export default function Silk({speed=5,scale=1,color='#C9A227',noiseIntensity=1.5,rotation=0}:{speed?:number;scale?:number;color?:string;noiseIntensity?:number;rotation?:number}){const uniforms=useMemo(()=>({uSpeed:{value:speed},uScale:{value:scale},uNoiseIntensity:{value:noiseIntensity},uColor:{value:new Color(...rgb(color))},uRotation:{value:rotation},uTime:{value:0}}),[]);useEffect(()=>{uniforms.uSpeed.value=speed;uniforms.uScale.value=scale;uniforms.uNoiseIntensity.value=noiseIntensity;uniforms.uColor.value.setRGB(...rgb(color));uniforms.uRotation.value=rotation},[speed,scale,color,noiseIntensity,rotation,uniforms]);return <Canvas dpr={[1,2]} frameloop="always"><Plane uniforms={uniforms}/></Canvas>}
