'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, CalendarBlank, CaretLeft, CaretRight, ChatCircleText, Check, ClipboardText, HandHeart, ShieldCheck, Sparkle, UserCircle } from '@phosphor-icons/react'
import { CTA, Footer, FinalCTA, Header, SocialRail } from './components/Chrome'
import { menuGroups, photos, treatments } from './data'

const PER_VIEW = 5
const featured = treatments.filter(t => t.featured)

const journey = [
  { n: '01', title: 'Consultation', copy: 'Discuss your concerns, goals and treatment options.', Icon: ChatCircleText },
  { n: '02', title: 'Personalised plan', copy: 'Receive clear recommendations based on your individual needs.', Icon: ClipboardText },
  { n: '03', title: 'Treatment', copy: 'Your chosen treatment is performed with care and precision.', Icon: Sparkle },
  { n: '04', title: 'Aftercare', copy: 'Receive guidance and support throughout your recovery and results.', Icon: HandHeart },
]

function TreatmentSlider() {
  const [start, setStart] = useState(0)
  const maxStart = Math.max(0, featured.length - PER_VIEW)
  return <div><div className="treatment-grid">{featured.slice(start, start + PER_VIEW).map(t => <article className="treatment-card" key={t.slug}><div className="treatment-image"><Image src={t.image} alt="" fill sizes="(max-width: 700px) 85vw, 20vw" /></div><div className="treatment-copy"><Sparkle size={16} className="gold" /><h3>{t.name}</h3><p>{t.short}</p><a href={`/treatments#${t.slug}`}>Explore treatment <ArrowRight size={14} /></a></div></article>)}</div><div className="slider-controls"><span>{String(start + 1).padStart(2, '0')} / {String(maxStart + 1).padStart(2, '0')}</span><div><button aria-label="Previous treatments" disabled={start === 0} onClick={() => setStart(Math.max(0, start - 1))}><CaretLeft size={18} /></button><button aria-label="Next treatments" disabled={start >= maxStart} onClick={() => setStart(Math.min(maxStart, start + 1))}><CaretRight size={18} /></button></div></div></div>
}

function AlsoStrip() {
  return <div className="also-strip">{menuGroups.map(g => <a className="also-item" href={`/treatments#${g.slug}`} key={g.slug}><div className="also-image"><Image src={g.image} alt="" fill sizes="(max-width: 700px) 90vw, 44vw" /></div><div className="also-copy"><h3>{g.name}</h3><p>{g.items.length} to choose from, prepared after a consultation</p><span className="text-link">View the list <ArrowRight size={14} /></span></div></a>)}</div>
}

export default function Page() {
  return <><Header /><SocialRail /><main>
    <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">Advanced aesthetics · London</p><h1>Refined aesthetics.<br /><em>Naturally you.</em></h1><p className="hero-text">Advanced aesthetic treatments designed to enhance your natural features, restore confidence and deliver beautifully considered results.</p><div className="hero-actions"><CTA><CalendarBlank size={15} />Book a Consultation</CTA><a href="#treatments" className="text-link">Explore treatments <ArrowRight size={15} /></a></div></div><div className="hero-visual"><Image src={photos.hero} alt="Woman with natural, glowing skin" fill priority sizes="(max-width: 900px) 100vw, 52vw" /><span className="image-note">Quiet care · considered results</span></div></section>
    <section id="about" className="editorial about"><div className="editorial-image tall"><Image src={photos.philosophy} alt="A calm skincare consultation" fill sizes="(max-width: 900px) 100vw, 48vw" /></div><div className="editorial-copy"><p className="eyebrow">01 · Personalise</p><h2>A more considered approach to aesthetics</h2><p>Every face has its own character. Our consultations are unhurried, our recommendations are thoughtful, and every treatment plan is shaped around you.</p><p>With clinical expertise and a light touch, we focus on natural-looking results that leave you feeling comfortable, confident and still entirely yourself.</p><a href="#contact" className="text-link">Meet the clinic <ArrowRight size={15} /></a></div></section>
    <section id="treatments" className="section section-soft"><div className="section-head"><div><p className="eyebrow">The treatment menu</p><h2>Advanced treatments,<br />carefully chosen</h2></div><div className="section-head-aside"><p>Explore treatments designed to refresh, restore and enhance your natural features, alongside our IV drips and vitamin injections.</p><a href="/treatments" className="text-link">View all treatments <ArrowRight size={15} /></a></div></div><TreatmentSlider /><AlsoStrip /></section>
    <section className="editorial feature"><div className="editorial-copy"><p className="eyebrow">Featured treatment</p><h2>Skin rejuvenation<br /><em>with a lighter touch.</em></h2><p>A considered programme to improve hydration, texture and luminosity over time, with recommendations tailored to your skin.</p><ul><li><Check size={16} />For tired, dull or uneven skin</li><li><Check size={16} />A gradual, natural-looking change</li><li><Check size={16} />Plan shaped in consultation</li></ul><CTA href="/treatments#skin-rejuvenation">Explore treatment <ArrowRight size={15} /></CTA></div><div className="editorial-image feature-image"><Image src={photos.feature} alt="Skincare treatment detail" fill sizes="(max-width: 900px) 100vw, 50vw" /></div></section>
    <section id="results" className="section results"><div className="section-head"><div><p className="eyebrow">Results</p><h2>Real results.<br />Beautifully considered.</h2></div><p>Genuine clinic photography will be added here once approved. We never present stock imagery as treatment results.</p></div><div className="results-placeholder"><div className="placeholder-pair"><div><Image src={photos.placeholder} alt="Development placeholder for approved results photography" fill sizes="45vw" /><span>Before · placeholder</span></div><div><Image src={photos.placeholder} alt="Development placeholder for approved results photography" fill sizes="45vw" /><span>After · placeholder</span></div></div><div><p className="eyebrow">Development placeholder</p><p className="placeholder-copy">Individual results vary. Treatment suitability is assessed during consultation.</p></div></div></section>
    <section className="section why"><p className="eyebrow">The clinic difference</p><h2>Why London Advanced<br />Aesthetic Clinic</h2><div className="why-grid">{[['Personalised care', 'Every treatment plan begins with understanding you, your features and your goals.', UserCircle], ['Natural results', 'Our approach is focused on subtle, balanced results that still look like you.', Sparkle], ['Advanced techniques', 'Thoughtful use of modern aesthetic treatments and techniques.', ShieldCheck], ['Complete support', 'From consultation through aftercare, every stage is carefully considered.', Check]].map(([title, copy, Icon]) => <div className="why-item" key={title as string}><Icon size={21} className="gold" /><h3>{title as string}</h3><p>{copy as string}</p></div>)}</div></section>
    <section className="clinic-banner"><Image src={photos.clinic} alt="Refined treatment room in a London clinic" fill sizes="100vw" /><div className="clinic-overlay"><p className="eyebrow">The clinic</p><h2>A calm space in the heart of London</h2><p>Private, comfortable and quietly refined, designed around your visit.</p><a href="#contact" className="text-link light">Visit the clinic <ArrowRight size={15} /></a></div></section>
    <section className="journey section"><div className="section-head"><div><p className="eyebrow">Your treatment journey</p><h2>Clear at every step</h2></div><p>From the first conversation to aftercare, you will know what to expect.</p></div><ol className="journey-grid">{journey.map(({ n, title, copy, Icon }) => <li className="journey-step" key={n}><span className="journey-node" aria-hidden="true"><Icon size={23} /></span><span className="journey-num">{n}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><div className="journey-cta"><p>Every journey begins with a conversation, and there is never any obligation to book.</p><CTA><CalendarBlank size={15} />Book a Consultation</CTA></div></section>
    <FinalCTA />
  </main><Footer /></>
}
