'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, CalendarBlank, CaretLeft, CaretRight, Check, Envelope, List, MapPin, Phone, ShieldCheck, Sparkle, UserCircle, X } from '@phosphor-icons/react'

const photos = {
  hero: 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=1500&q=88',
  philosophy: 'https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&w=1000&q=88',
  feature: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=88',
  clinic: 'https://images.unsplash.com/photo-1519824145371-296894a0daa9?auto=format&fit=crop&w=1600&q=88',
  placeholder: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=85',
}

const treatments = [
  ['Anti-Wrinkle Treatments', 'Soften lines while preserving expression', 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=700&q=82'],
  ['Dermal Fillers', 'Restore balance and subtle definition', 'https://images.unsplash.com/photo-1573461160327-b450ce3d8e7f?auto=format&fit=crop&w=700&q=82'],
  ['Skin Boosters', 'Deep hydration for a brighter complexion', 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=700&q=82'],
  ['Polynucleotides', 'Support skin quality and resilience', 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=700&q=82'],
  ['Profhilo', 'A considered approach to skin laxity', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=700&q=82'],
  ['Microneedling', 'Encourage a smoother, fresher texture', 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=700&q=82'],
]

function CTA({ children, secondary = false }: { children: React.ReactNode; secondary?: boolean }) {
  return <a href="#contact" className={`cta ${secondary ? 'cta-secondary' : ''}`}>{children}</a>
}

function Logo() { return <a href="#home" className="logo" aria-label="London Advanced Aesthetic Clinic"><span className="logo-mark">LA</span><span>London Advanced<br />Aesthetic Clinic</span></a> }

function Header() {
  const [open, setOpen] = useState(false)
  const links = [['Home', '#home'], ['Treatments', '#treatments'], ['Results', '#results'], ['About', '#about'], ['Contact', '#contact']]
  return <header className="site-header"><div className="header-inner"><Logo /><nav className="desktop-nav">{links.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="header-action"><CTA><CalendarBlank size={15} />Book a Consultation</CTA></div><button className="menu-trigger" aria-label="Open menu" onClick={() => setOpen(true)}><List size={24} /></button></div>{open && <div className="mobile-menu"><div className="mobile-menu-top"><Logo /><button aria-label="Close menu" onClick={() => setOpen(false)}><X size={24} /></button></div><nav>{links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{label}</a>)}</nav><CTA><CalendarBlank size={15} />Book a Consultation</CTA></div>}</header>
}

function TreatmentSlider() {
  const [start, setStart] = useState(0)
  return <div><div className="treatment-grid">{treatments.slice(start, start + 5).map(([name, desc, src]) => <article className="treatment-card" key={name}><div className="treatment-image"><Image src={src} alt="" fill sizes="(max-width: 700px) 85vw, 20vw" /></div><div className="treatment-copy"><Sparkle size={16} className="gold" /><h3>{name}</h3><p>{desc}</p><a href="#contact">Explore treatment <ArrowRight size={14} /></a></div></article>)}</div><div className="slider-controls"><span>{String(start + 1).padStart(2, '0')} / 02</span><div><button aria-label="Previous treatments" disabled={start === 0} onClick={() => setStart(Math.max(0, start - 1))}><CaretLeft size={18} /></button><button aria-label="Next treatments" disabled={start >= 1} onClick={() => setStart(Math.min(1, start + 1))}><CaretRight size={18} /></button></div></div></div>
}

export default function Page() {
  return <><Header /><main>
    <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">Advanced aesthetics · London</p><h1>Refined aesthetics.<br /><em>Naturally you.</em></h1><p className="hero-text">Advanced aesthetic treatments designed to enhance your natural features, restore confidence and deliver beautifully considered results.</p><div className="hero-actions"><CTA><CalendarBlank size={15} />Book a Consultation</CTA><a href="#treatments" className="text-link">Explore treatments <ArrowRight size={15} /></a></div></div><div className="hero-visual"><Image src={photos.hero} alt="Woman with natural, glowing skin" fill priority sizes="(max-width: 900px) 100vw, 52vw" /><span className="image-note">Quiet care · considered results</span></div></section>
    <section className="trust-strip"><div>Advanced treatments</div><div>Personalised care</div><div>Natural-looking results</div><div>Private London clinic</div></section>
    <section id="about" className="editorial about"><div className="editorial-image tall"><Image src={photos.philosophy} alt="A calm skincare consultation" fill sizes="(max-width: 900px) 100vw, 48vw" /></div><div className="editorial-copy"><p className="eyebrow">01 · Personalise</p><h2>A more considered approach to aesthetics</h2><p>Every face has its own character. Our consultations are unhurried, our recommendations are thoughtful, and every treatment plan is shaped around you.</p><p>With clinical expertise and a light touch, we focus on natural-looking results that leave you feeling comfortable, confident and still entirely yourself.</p><a href="#contact" className="text-link">Meet the clinic <ArrowRight size={15} /></a></div></section>
    <section id="treatments" className="section section-soft"><div className="section-head"><div><p className="eyebrow">The treatment menu</p><h2>Advanced treatments,<br />carefully chosen</h2></div><p>Explore treatments designed to refresh, restore and enhance your natural features.</p></div><TreatmentSlider /></section>
    <section className="editorial feature"><div className="editorial-copy"><p className="eyebrow">Featured treatment</p><h2>Skin rejuvenation<br /><em>with a lighter touch.</em></h2><p>A considered programme to improve hydration, texture and luminosity over time, with recommendations tailored to your skin.</p><ul><li><Check size={16} />For tired, dull or uneven skin</li><li><Check size={16} />A gradual, natural-looking change</li><li><Check size={16} />Plan shaped in consultation</li></ul><CTA>Explore treatment <ArrowRight size={15} /></CTA></div><div className="editorial-image feature-image"><Image src={photos.feature} alt="Skincare treatment detail" fill sizes="(max-width: 900px) 100vw, 50vw" /></div></section>
    <section id="results" className="section results"><div className="section-head"><div><p className="eyebrow">Results</p><h2>Real results.<br />Beautifully considered.</h2></div><p>Genuine clinic photography will be added here once approved. We never present stock imagery as treatment results.</p></div><div className="results-placeholder"><div className="placeholder-pair"><div><Image src={photos.placeholder} alt="Development placeholder for approved results photography" fill sizes="45vw" /><span>Before · placeholder</span></div><div><Image src={photos.placeholder} alt="Development placeholder for approved results photography" fill sizes="45vw" /><span>After · placeholder</span></div></div><div><p className="eyebrow">Development placeholder</p><p className="placeholder-copy">Individual results vary. Treatment suitability is assessed during consultation.</p></div></div></section>
    <section className="section why"><p className="eyebrow">The clinic difference</p><h2>Why London Advanced<br />Aesthetic Clinic</h2><div className="why-grid">{[['Personalised care', 'Every treatment plan begins with understanding you, your features and your goals.', UserCircle], ['Natural results', 'Our approach is focused on subtle, balanced results that still look like you.', Sparkle], ['Advanced techniques', 'Thoughtful use of modern aesthetic treatments and techniques.', ShieldCheck], ['Complete support', 'From consultation through aftercare, every stage is carefully considered.', Check]].map(([title, copy, Icon]) => <div className="why-item" key={title as string}><Icon size={21} className="gold" /><h3>{title as string}</h3><p>{copy as string}</p></div>)}</div></section>
    <section className="clinic-banner"><Image src={photos.clinic} alt="Refined treatment room in a London clinic" fill sizes="100vw" /><div className="clinic-overlay"><p className="eyebrow">The clinic</p><h2>A calm space in the heart of London</h2><p>Private, comfortable and quietly refined, designed around your visit.</p><a href="#contact" className="text-link light">Visit the clinic <ArrowRight size={15} /></a></div></section>
    <section className="journey section"><div className="section-head"><div><p className="eyebrow">Your treatment journey</p><h2>Clear at every step</h2></div><p>From the first conversation to aftercare, you will know what to expect.</p></div><div className="journey-grid">{[['01', 'Consultation', 'Discuss your concerns, goals and treatment options.'], ['02', 'Personalised plan', 'Receive clear recommendations based on your individual needs.'], ['03', 'Treatment', 'Your chosen treatment is performed with care and precision.'], ['04', 'Aftercare', 'Receive guidance and support throughout your recovery and results.']].map(([number, title, copy]) => <div className="journey-step" key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
    <section id="contact" className="final-cta"><p className="eyebrow">Begin with a conversation</p><h2>Your best look starts<br />with a conversation.</h2><p>Book a private consultation and discover the treatments suited to you.</p><div><CTA><CalendarBlank size={15} />Book a Consultation</CTA><a href="mailto:hello@londonadvancedaesthetics.co.uk" className="text-link">Contact the clinic <ArrowRight size={15} /></a></div></section>
  </main><footer className="footer"><div className="footer-grid"><div><Logo /><p>Refined aesthetic care, thoughtfully tailored in London.</p></div><div><p className="footer-label">Explore</p><a href="#treatments">Treatments</a><a href="#results">Results</a><a href="#about">About</a></div><div><p className="footer-label">Connect</p><p><Envelope size={15} /> hello@londonadvancedaesthetics.co.uk</p><p><Phone size={15} /> Contact details to be supplied</p><p><MapPin size={15} /> London, United Kingdom</p></div></div><div className="footer-bottom"><span>© 2026 London Advanced Aesthetic Clinic</span><span>Privacy · Terms · Cookies</span></div></footer></>
}
